name: HungerGames
main: tk.shanebee.hg.HG
authors: [bob7l, Spoopy, ShaneBee]
description: A Simple, fun, PvP arena plugin
version: '${project.version}'
website: https://bitbucket.org/ShaneBeeStudios/hungergames
api-version: '1.13'
softdepend: [Multiverse-Core, MultiWorld, Vault, My_Worlds, GoldenEnchants, mcMMO, MythicMobs, PlaceholderAPI, XConomy]

commands:
  hg:
    description: HungerGames Base command
permissions:
  hg.join:
    description: Permission to join the game using /hg join
    default: true
  hg.leave:
    description: Permission to leave the game using /hg leave
    default: true
  hg.kit:
    description: Permission to get kits using /hg kit <kitname>
    default: true
  hg.listgames:
    description: Permission to see all the available games
    default: true
  hg.list:
    description: Permission to see a list of players in a game
    default: true
  hg.forcestart:
    description: Permission to give forcestart item
    default: false